### ISSUE TITLE
Website pages have no title

### ISSUE THREAD

**Issue by nickerso** [Physiome/journal-website#160]
It seems that none of the website pages have HTML titles set, so all pages just show up with the page URL in the title bar. Would be nice if each page had a relevant title. Or at least a generic `Physiome` title by default.

![image](https://user-images.githubusercontent.com/811244/145743147-c03fce89-9931-468e-9687-1aefb2e94379.png)

**Comment by s-fong** [comment]
These are added, to be the same as the title of the page.
